name: Mise a jour IA
on:
  schedule:
    - cron: '0 6,11,16 * * 1-5' # 7h, 12h, 17h (Heure Paris)
  workflow_dispatch: # Permet de le lancer à la main pour tester
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Libs
        run: pip install yfinance openai
      - name: Run Script
        env:
          MAMMOUTH_API_KEY: ${{ secrets.MAMMOUTH_API_KEY }}
        run: python updateData.py
      - name: Save Result
        run: |
          git config --global user.name 'Robot-IA'
          git config --global user.email 'bot@bot.com'
          git add index.html
          git commit -m "Mise à jour automatique" || echo "Rien à changer"
          git push
